export const categories = [
  {
    id: 1,
    text: 'Immobilier',
    sublinks: [
      'Tout Immobilier',
      'Ventes immobilières',
      'Locations',
      'Colocations',
      'Bureaux & Commerces',
    ],
  },
  {
    id: 2,
    text: 'Véhicules',
    sublinks: [
      'Tout Véhicules',
      'Voitures',
      'Motos',
      'Caravaning',
      'Utilitaires',
      'Camions',
      'Nautisme',
      'Équipement auto',
    ],
  },
  {
    id: 3,
    text: 'Vacances',
    sublinks: [
      'Locations en France',
      'Hôtels',
      'Ventes privées vacances',
      'Locations en Espagne',
    ],
  },
  {
    id: 4,
    text: 'Emploi',
    sublinks: [
      'Tout Emploi',
      "Offres d'emploi",
      'Formations professionnelles',
      "Offres d'emploi Cadres",
    ],
  },
  {
    id: 5,
    text: 'Mode',
    sublinks: [
      'Tout Mode',
      'Vêtements',
      'Chaussures',
      'Vêtements bébé',
      'Équipement bébé',
      'Montres & Bijoux',
      'Accessoires & Bagagerie',
      'Luxe et tendance',
    ],
  },
  {
    id: 6,
    text: 'Maison',
    sublinks: [
      'Tout Maison',
      'Ammeublement',
      'Électroménager',
      'Arts de la table',
      'Décoration',
      'Linge de maison',
      'Bricolage',
      'Jardinage',
    ],
  },
  {
    id: 7,
    text: 'Multimédia',
    sublinks: [
      'Tout Multimédia',
      'Informatique',
      'Image & Son',
      'Consoles & Jeux vidéo',
      'Téléphonie',
    ],
  },
  {
    id: 8,
    text: 'Loisirs',
    sublinks: [
      'Tout Loisirs',
      'DVD - Films',
      'CD - Musique',
      'Livres',
      'Vélos',
      'Sports & Hobbies',
      'Instruments de musique',
      'Collection',
      'Jeux & Jouets',
      'Vins & Gastronomie',
    ],
  },
  {
    id: 9,
    text: 'Matériel professionnel',
    sublinks: [
      'Tout Matériel professionnel',
      'Matériel agricole',
      'Transport - Manutention',
      'BTP - Chantier gros-oeuvre',
      'Outillage - Matériaux 2nd-oeuvre',
      'Équipements industriels',
      'Restauration - Hôtellerie',
      'Fournitures de bureau',
      'Commerces & Marchés',
      'Matériel médical',
    ],
  },
  {
    id: 10,
    text: 'Autres',
    sublinks: [
      'Tout Services',
      'Prestations de services',
      'Billetterie',
      'Évènements',
      'Cous particuliers',
      'Covoiturage',
      'Animaux',
      'Autre',
    ],
  },
]
